# Site settings
title: Ethan J. Jackson
email: ejj@eecs.berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
    Personal website for Ethan J. Jackson.  A major contributer to the Open
    vSwitch project, and a first year PhD student at UC Berkeley studying
    Computer Networks and Distributed Systems.
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
